SET NOCOUNT ON;

EXEC pbist_sccm.sp_populatecomputer;
EXEC pbist_sccm.sp_populatecomputermalware;
EXEC pbist_sccm.sp_populatecomputerprogram;
EXEC pbist_sccm.sp_populatecomputerupdate;
EXEC pbist_sccm.sp_populatemalware;
EXEC pbist_sccm.sp_populateprogram;
EXEC pbist_sccm.sp_populatescanhistory;
EXEC pbist_sccm.sp_populatesite;
EXEC pbist_sccm.sp_populateupdate;
EXEC pbist_sccm.sp_populateuser;
EXEC pbist_sccm.sp_populateusercomputer;
EXEC pbist_sccm.sp_populatecollection;
EXEC pbist_sccm.sp_populatecomputercollection;

EXEC pbist_sccm.sp_populate_ClientHealthSummary;
EXEC pbist_sccm.sp_populate_ComponentStatus;
EXEC pbist_sccm.sp_populate_DistributionPointsStatus;
EXEC pbist_sccm.sp_populate_OverallComplianceBaseline;
EXEC pbist_sccm.sp_populate_ReplicationStatus;
EXEC pbist_sccm.sp_populate_SoftwareDistribution;
EXEC pbist_sccm.sp_populate_TaskSequenceDeployment;
EXEC pbist_sccm.sp_populate_ClientHealthClientInstalledVersionDetails;
EXEC pbist_sccm.sp_populate_ClientHealthClientsinventorystatisticslast30days;
EXEC pbist_sccm.sp_populate_ClientHealthCountAssignedClientsBySite;
EXEC pbist_sccm.sp_populate_ClientHealthCountClientsInstalledVersion;
EXEC pbist_sccm.sp_populate_ClientHealthCountClientsInstalledVersionPerSite;
EXEC pbist_sccm.sp_populate_ClientHealthEvaluationCount;
EXEC pbist_sccm.sp_populate_ClientHealthWUAVersionAllClients;
EXEC pbist_sccm.sp_populate_ComplianceSettingComplianceByComputers;
EXEC pbist_sccm.sp_populate_ComplianceSettingComplianceCIForAllBaseline;
EXEC pbist_sccm.sp_populate_ConfigMgrServerHealthBackupStatus;
EXEC pbist_sccm.sp_populate_ConfigMgrServerHealthComponentStatusDetails;
EXEC pbist_sccm.sp_populate_ConfigMgrServerHealthCountComponentStatusMessagesBySeverity;
EXEC pbist_sccm.sp_populate_DistributionPointsCompliancebyDPStatus;
EXEC pbist_sccm.sp_populate_DistributionPointsCompliancebyPackagesStatus;
EXEC pbist_sccm.sp_populate_DistributionPointsConfigurationStatus;
EXEC pbist_sccm.sp_populate_ReplicationStatusReplicationGroup;
EXEC pbist_sccm.sp_populate_ReplicationStatusDetails
EXEC pbist_sccm.sp_populate_SoftwareDistributionOverallApplicationDeployment;
EXEC pbist_sccm.sp_populate_SoftwareDistributionOverallPackageDeployment;
EXEC pbist_sccm.sp_populate_SoftwareDistributionOverallPckAPPDPdistribution;
EXEC pbist_sccm.sp_populate_TasksequenceDPContentStatusReferencedPackagesTaskSequence;
EXEC pbist_sccm.sp_populate_TasksequenceOverallTaskSequenceByComputerDeployment;
EXEC pbist_sccm.sp_populate_TasksequenceOverallTaskSequencebyTaskSequenceDeployment;

DELETE FROM pbist_sccm.[configuration] WHERE name='lastLoadTimestamp' AND configuration_group='SolutionTemplate' AND configuration_subgroup='System Center';
INSERT INTO pbist_sccm.[configuration](configuration_group, configuration_subgroup, NAME, [value], [visible]) VALUES ('SolutionTemplate', 'System Center', 'lastLoadTimestamp', GetDate(), 1);
