export const EN_US = {
    ADF_EMAILS: `Enter one or more email addresses that will be notified when the data movement process fails.`,
    ADF_EMAILS_TITLE: `Multiple email adresses need to be comma separated.`,
    APP_CONTACT_US: `CONTACT US`,
    APP_CONTACT_US_LINK: `mailto:PBISolnTemplates@microsoft.com`,
    APP_EXPERIENCING_AN_ERROR: `Experiencing an error? Click here to let us know.`,
    APP_MICROSOFT: `Microsoft`,
    APP_POWER_BI: `Power BI`,
    APP_PRIVACY_COOKIES: `PRIVACY & COOKIES`,
    APP_PRIVACY_COOKIES_LINK: `https://www.microsoft.com/en-us/privacystatement/OnlineServices/Default.aspx`,
    APP_TERMS_USE: `TERMS OF USE`,
    APP_TERMS_USE_LINK: `https://www.microsoft.com/en-us/legal/intellectualproperty/copyright/default.aspx`,
    APP_TRADEMARKS: `TRADEMARKS`,
    APP_TRADEMARKS_LINK: `https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/en-us.aspx`,
    AZURE_ANALYSIS_PROVISIONING: `Would you like us to provision a new SSAS instance or use an existing SSAS instance?`,
    AZURE_LOGIN_BING_TEXT: `You can read the Bing Terms of Use`,
    AZURE_LOGIN_COGNITIVE_TEXT: `You can read the Congitive Services Terms of Use`,
    AZURE_LOGIN_CONNECT: `Connect to Azure`,
    AZURE_LOGIN_CONNECTION: `How are you signing in to your Azure subscription?`,
    AZURE_LOGIN_DIRECTORY: `Azure Tenant:`,
    AZURE_LOGIN_DIRECTORY_ADDRESS: `directoryname.onmicrosoft.com`,
    AZURE_LOGIN_DIRECTORY_DESCRIPTION: `guide`,
    AZURE_LOGIN_DIRECTORY_LINK: `http://community.powerbi.com/t5/Power-BI-Solution-Templates/Guide-for-using-Microsoft-accounts-with-Twitter-template/m-p/60088#M31`,
    AZURE_LOGIN_DIRECTORY_TEXT: `Enter the name of the Azure tenant you want to connect to. It usually looks like contoso.com or contoso.onmicrosoft.com. Not sure? Take a look at this `,
    AZURE_LOGIN_DONT_HAVE: `I don't have an Azure subscription`,
    AZURE_LOGIN_GET_STARTED: `Get started with a free`,
    AZURE_LOGIN_HAVE: `I have an Azure subscription`,
    AZURE_LOGIN_LINK: `https://azure.microsoft.com/en-us/free/`,
    AZURE_LOGIN_LINK_DESCRIPTION: `Azure subscription trial`,
    AZURE_LOGIN_MICROSOFT: `Personal Microsoft account (created by you)`,
    AZURE_LOGIN_ORGANIZATIONAL: `Work or school account (created by your IT department)`,
    AZURE_LOGIN_PRICING_TEXT: `View current Azure pricing`,
    AZURE_LOGIN_PRICING_CALCULATOR_TEXT: `You can learn more about the specific Azure resources created by this template and how to calculate estimated costs`,
    AZURE_LOGIN_RESOURCE_GROUP: `Azure Resource Group Name:`,
    AZURE_LOGIN_SUBSCRIPTION: `Azure Subscription:`,
    AZURE_LOGIN_SUBSCRIPTION_ERROR: `You do not have any Azure subscriptions linked to your account. You can get started with a free trial by clicking the link at the top of the page.`,
    AZURE_LOGIN_SUBSCRIPTION_ERROR_CRM: `You do not have any Azure subscriptions linked to your CRM account and tenant.`,
    AZURE_LOGIN_SUBTITLE: `To create the solution we will be using a number of Azure Services which require an Azure subscription.`,
    AZURE_LOGIN_UNKNOWN_ERROR: `You do not have any Azure subscriptions linked to your account. You can get started with a free trial by clicking the link at the top of the page.`,
    CHOOSE_SSAS_AZURE_ANALYSIS_SERVICES: `Azure Analysis Services`,
    CHOOSE_SSAS_DATA_STORAGE_MODE: `Data Storage Mode:`,
    CHOOSE_SSAS_DESCRIPTION: `Power BI with Azure Analysis Services is recommended for enterprise-grade deployments for larger System Center Configuration Manager installations (more than 100,000 users or devices), to support additional analytics tools such as Excel, or to provide a finer grain of control on how data is loaded into Power BI. The Azure Analysis Services standard tier incurs an additional cost of $1.015/hr.`,
    CHOOSE_SSAS_DESCRIPTION2: `Importing data into Power BI is recommended for small to medium sized System Center Configuration Manager installations.`,
    CHOOSE_SSAS_IMPORT_TO_PBI: `Import to Power BI`,
    CHOOSE_SSAS_LEARN_MORE: `Learn more about Azure Analysis Services`,
    CHOOSE_SSAS_LEARN_MORE_LINK: `https://azure.microsoft.com/en-us/services/analysis-services/`,
    COMMON_ADVANCED_OPTIONAL: `Advanced (optional)`,
    COMMON_AND: `and`,
    COMMON_CHECK_OUT_THE: `Check out the`,
    COMMON_CONNECT: `Connect`,
    COMMON_CUSTOMIZE: `Customize`,
    COMMON_DOWNLOAD: `Download`,
    COMMON_EVALUATION: `For evaluation purposes only. Not intended for production use.`,
    COMMON_FOR_DETAILS: `for details.`,
    COMMON_FOR_MORE_DETAILS: `for more details.`,
    COMMON_HERE: `here`,
    COMMON_MONTH_0: `January`,
    COMMON_MONTH_1: `February`,
    COMMON_MONTH_2: `March`,
    COMMON_MONTH_3: `April`,
    COMMON_MONTH_4: `May`,
    COMMON_MONTH_5: `June`,
    COMMON_MONTH_6: `July`,
    COMMON_MONTH_7: `August`,
    COMMON_MONTH_8: `September`,
    COMMON_MONTH_9: `October`,
    COMMON_MONTH_10: `November`,
    COMMON_MONTH_11: `December`,
    COMMON_MS_PRIVACY_POLICY: `Microsoft's Privacy Policy`,
    COMMON_NO: `No`,
    COMMON_OPTIONAL: `(Optional)`,
    COMMON_PASSWORD: `password`,
    COMMON_REGISTER: `Register`,
    COMMON_ROW: `Row`,
    COMMON_ROWS: `Rows`,
    COMMON_RUN: `Run`,
    COMMON_SEE: `See`,
    COMMON_SHOW_DOWNLOAD: `Since you are copying your data into SQL Server, you will need to use our local installer to set up the template. In order to download the solution template installer, please click the Download button below.`,
    COMMON_SUBSCRIBE: `Subscribe`,
    COMMON_TOKEN: `token`,
    COMMON_UNINSTALL: `Uninstall`,
    COMMON_UNKNOWN_ERROR: `Unknown Error has occured`,
    COMMON_USERNAME: `username`,
    COMMON_VALIDATE: `Validate`,
    COMMON_YES: `Yes`,
    CUSTOMIZE_ACTUAL_REVENUE: `Where do you want to pull your actual revenue from?`,
    CUSTOMIZE_ACTUAL_REVENUE_DESCRIPTION: `By default, we use closed CRM opportunities to calculate actual revenue. If you are planning on bringing in actual sales from another source, you can choose to keep these blank.`,
    CUSTOMIZE_BASE_URL: `Base CRM URL:`,
    CUSTOMIZE_BASE_URL_DESCRIPTION: `If you would like to navigate back to your CRM directly from the Power BI report, we need your CRM domain URL (Example: https://yourorg.crm.dynamics.com)`,
    CUSTOMIZE_CLOSED_OPPORTUNITIES: `Closed opportunities`,
    CUSTOMIZE_DAILY_TRIGGER_TIME: `Daily Trigger Time:`,
    CUSTOMIZE_DATA_RETENTION_DAYS: `Data Retention Days:`,
    CUSTOMIZE_ENDPOINT_COMPLIANCE_TARGET: `Endpoint Compliance Target:`,
    CUSTOMIZE_HEALTH_EVALUATION_TARGET: `Health Evaluation Target:`,
    CUSTOMIZE_KEEP_BLANK: `Keep Blank`,
    CUSTOMIZE_SPECIFIC: `Make the template specific for you and your team.`,
    CUSTOMIZE_START_FISCAL_YEAR: `Start of fiscal year:`,
    CUSTOMIZE_RECURRENCE_OPTIONS: `Configure how often you want to do an incremental refresh:`,
    GETTING_STARTED_COMPANY: `Company:`,
    GETTING_STARTED_EMAIL: `Email:`,
    GETTING_STARTED_EMAIL_CONFIRMATION: `Email Confirmation:`,
    GETTING_STARTED_FIRST_NAME: `First Name:`,
    GETTING_STARTED_LAST_NAME: `Last Name:`,
    GETTING_STARTED_LIST_1: `To set up this solution template you will need:`,
    GETTING_STARTED_LIST_2: `Features of this architecture:`,
    GETTING_STARTED_NEW_VERSION: `There's a new version available!`,
    GETTING_STARTED_NEW_VERSION_INFO: `Download the latest installer so you're up to date.`,
    GETTING_STARTED_REGISTRATION_ERROR: `Invalid name, company, or email`,
    GETTING_STARTED_REGISTRATION_ERROR_EMAIL: `Invalid email domain`,
    GETTING_STARTED_TITLE: `Get started with`,
    KEYVAULT_LOGIN_ERROR: `An error occurred while connecting to the Azure Key Vault Service.`,
    KEYVAULT_LOGIN_SUBTITLE: `We now need to set up a connection to the Azure Key Vault.`,
    KEYVAULT_LOGIN_TITLE: `Connect to Azure Key Vault`,
    MSCRM_LOGIN_CONNECT: `Connect to my Azure Subscription with Dynamics 365`,
    MSCRM_LOGIN_ERROR: `An error occurred while connecting to the Dynamics 365 Export Service.`,
    // MSCRM_LOGIN_NO_AUTHORIZATION: `No Dynamics 365 organizations were found in which your account has Administrator privileges.`,
    MSCRM_LOGIN_NO_ORGANIZATIONS: `No Dynamics 365 Organizations Found.`,
    // MSCRM_LOGIN_NO_OTHER: `No Dynamics 365 organizations were found in which your account can read organization metadata.`,
    MSCRM_LOGIN_ORGANIZATION: `Dynamics 365 Organization:`,
    MSCRM_LOGIN_SUBTITLE: `We now need to set up a connection to Dynamics 365.`,
    MSCRM_LOGIN_TITLE: `Connect to Dynamics 365`,
    NAVBAR_MICROSOFT_PRIVACY_STATEMENT: `Microsoft's Privacy Statement`,
    NAVBAR_MICROSOFT_PRIVACY_STATEMENT_LINK: `https://www.microsoft.com/en-us/privacystatement/OnlineServices/Default.aspx`,
    NAVBAR_TERMS_USE: `Terms of Use`,
    NAVBAR_TERMS_USE_LINK: `https://pbist.azurewebsites.net/pages/termsOfUse.html`,
    NAVIGATION_BACK: `Back`,
    NAVIGATION_LOGS: `Navigate here to view logs:`,
    NAVIGATION_MS_PRIVACY: `Information gathered is used by Microsoft to replicate information from the source application to the destination database. By using this solution template, you agree to Microsoft’s terms and privacy statement. Read the Microsoft privacy statement to learn more about how your information is used.`,
    NAVIGATION_MS_PRIVACY_LINK: `https://www.microsoft.com/en-us/privacystatement/OnlineServices/Default.aspx`,
    NAVIGATION_MS_PRIVACY_LINK_TEXT: `Microsoft Privacy Statement`,
    NAVIGATION_SUCCESSFULLY_VALIDATED: `Successfully validated`,
    NAVIGATION_VIEW_DETAILS: `View Details`,
    POWER_BI_SIGN_IN: 'Sign In',
    POWER_BI_SIGN_UP: 'Sign up free',
    POWER_BI_LEARN_MORE: 'Learn more',
    PROGRESS_ALL_DONE: `All done! You can now download your Power BI report and start exploring your data.`,
    PROGRESS_DOWNLOAD_PBIX: `Download Report`,
    PROGRESS_DOWNLOAD_PBIX_INFO: 'Open the Power BI report (.pbix file) to explore your data. Publish the report for others to see in your Power BI workspace. You will need Power BI Desktop to open this file - download it ',
    PROGRESS_DOWNLOAD_POWERAPP: `Download the PowerApp`,
    PROGRESS_DOWNLOAD_POWERAPP_INFO: 'If you or someone else needs to change the twitter query later, download the Power App (or .msapp file). Use PowerApps studio to run the app or share with others. Download PowerApps Studio',
    PROGRESS_GETTING_READY: `Getting your Power BI file ready...`,
    PROGRESS_GETTING_READY_POWERAPP: `Getting your PowerApp file ready...`,
    PROGRESS_OKAY: `Okay, let's get your deployment started!`,
    PROGRESS_SIGN_UP: `Sign up to stay connected with the solution template engineering team with information about new templates, enhancements, tips and tricks.`,
    PROGRESS_SUBTITLE: `This might take a while. We'll show you progress while you wait. Please don't close the browser until all the steps are completed. The setup could take 10-15 minutes.`,
    PROGRESS_TITLE: `Track your progress`,
    PROGRESS_UNSUBSCRIBE: `You can unsubscribe at any time.`,
    RECURRENT_NEVER: `Never`,
    RECURRENT_15_MINUTES: `Every 15 minutes`,
    RECURRENT_30_MINUTES: `Every 30 minutes`,
    RECURRENT_HOURLY: `Hourly`,
    RECURRENT_DAILY: `Daily`,
    SALESFORCE_LOGIN_PASSWORD: `Salesforce Password:`,
    SALESFORCE_LOGIN_SUBTITLE: `We now need to set up a connection to Salesforce in order to pull data.`,
    SALESFORCE_LOGIN_TITLE: `Login to Salesforce`,
    SALESFORCE_LOGIN_TOKEN: `Salesforce Token:`,
    SALESFORCE_LOGIN_TOKEN_DESCRIPTION: `If you do not know what your security token is, or how to get it, please contact your Salesforce administrator.`,
    SALESFORCE_LOGIN_URL: `Salesforce Online URL:`,
    SALESFORCE_LOGIN_USERNAME: `Salesforce Username:`,
    SAP_APPLICATION_SERVER: `Application Server: `,
    SAP_APPLICATION_SERVER_DESCRIPTION: `Name of the host to which you want to connect.`,
    SAP_CLIENT: `Client: `,
    SAP_CLIENT_DESCRIPTION: `Always three numeric characters.`,
    SAP_INSTANCE_NUMBER: `Instance Number: `,
    SAP_INSTANCE_NUMBER_DESCRIPTION: `Instance number of the SAP system to which you want to connect. Always two numeric digits. Formerly called System Number.`,
    SAP_LANGUAGE: `Language:`,
    SAP_PASSWORD: `Password:`,
    SAP_ROUTER_STRING: `SAP Router String:`,
    SAP_ROW_BATCH_SIZE: `Row Batch Size:`,
    SAP_TITLE: `SAP Source System Connection Information`,
    SAP_SYSTEM_ID: `System ID: `,
    SAP_SYSTEM_ID_DESCRIPTION: `System ID of the SAP system to which you want to connect.`,
    SAP_USER: `User:`,
    SCRIBE_LOGIN_ORGANIZATION: `Scribe Organization:`,
    SCRIBE_LOGIN_PASSWORD: `Scribe Password:`,
    SCRIBE_LOGIN_SUBTITLE: `Let’s start by setting up your Scribe Account. Scribe is a third party service that enables you to pull data from Dynamics 365. When we run the setup, Scribe will copy all of your Dynamics 365 data into your database. Once all your data is copied, Scribe will only update new and changed records making future data pulls extremely fast.`,
    SCRIBE_LOGIN_TITLE: `Connect to your Scribe Account`,
    SCRIBE_LOGIN_USERNAME: `Scribe Username:`,
    SEARCH_TERMS_GUIDELINES: `Twitter search query guidelines`,
    SEARCH_TERMS_LINK: `https://dev.twitter.com/rest/public/search`,
    SEARCH_TERMS_QUERY: `Search Query:`,
    SEARCH_TERMS_QUERY_EXAMPLE: `@MSPowerBI OR Azure OR "Stream Analytics"`,
    SEARCH_TERMS_SUBTITLE: `Input the search terms you want to track. We will collect all tweets that match your search criteria. We can track hashtags, Twitter handles, plain text and more. For example, if you are interested in tweets that mention Azure or the Power BI Twitter handle, you would put: @MSPowerBI OR Azure.`,
    SEARCH_TERMS_TITLE: `Customize your search terms`,
    SUMMARY_SUBTITLE: `Please verify that the information provided below is correct. If you are ready click Run to begin building the solution template.This will also download the pbix file which you can begin exploring as soon as the setup finishes.`,
    SUMMARY_TITLE: `Verify and run solution`,
    SQL_SERVER_AUTHENTICATION: `Authentication: `,
    SQL_SERVER_CHECK_AVAILABILITY: `Check Availability`,
    SQL_SERVER_CREATING_NEW: `Creating a new SQL database, this may take 2-3 minutes`,
    SQL_SERVER_DATABASE: `Database:`,
    SQL_SERVER_DATABASE_RECOVERY: `(Simple/bulk recovery mode is recommended)`,
    SQL_SERVER_EXISTING: `Existing SQL Instance`,
    SQL_SERVER_IMPERSONATION: `This option will impersonate the previously chosen Windows user`,
    SQL_SERVER_LOCATION: `Server Location`,
    SQL_SERVER_NEW: `New Azure SQL Instance`,
    SQL_SERVER_PASSWORD: `Password: `,
    SQL_SERVER_PASSWORD_CONFIRMATION: `Password Confirmation:`,
    SQL_SERVER_PASSWORD_DESCRIPTION: `The password for the chosen windows account. This is required to pull data in an unattended mode.`,
    SQL_SERVER_PASSWORD_NEW_DESCRIPTION: `Password must be at least eight characters including one uppercase letter, one special character and one number.`,
    SQL_SERVER_PROVISION: `Would you like us to provision a new Azure SQL instance or use an existing SQL instance?`,
    SQL_SERVER_SERVER_NAME: `Server Name:`,
    SQL_SERVER_SKU: `Server Sku:`,
    SQL_SERVER_SKU_DESCRIPTION: `Performance and cost information for the different Azure SQL Database tiers are available`,
    SQL_SERVER_SKU_LINK: `https://azure.microsoft.com/en-us/pricing/details/sql-database/`,
    SQL_SERVER_SKU_P1: `P1`,
    SQL_SERVER_SKU_S1: `S1`,
    SQL_SERVER_SKU_S2: `S2`,
    SQL_SERVER_SKU_S3: `S3`,
    SQL_SERVER_STANDARD_AZURE: `We will create a Standard Azure instance inside your Azure Subscription.`,
    SQL_SERVER_USERNAME: `SQL Username:`,
    SQL_SERVER_USING_AZURE: `Using Azure SQL?`,
    SQL_SERVER_USING_GOV_AZURE: `Government Azure`,
    SQL_SERVER_WINDOWS: `Windows Username: `,
    SQL_SERVER_WINDOWS_DESCRIPTION: `Must be in <domain>\<username> or <machinename>\<username> format`,
    SSAS_SUBTITLE: `Would you like to use Azure Analysis Services? Azure Analysis Services scales beyond the Power BI 1GB compressed data limit and has better performance.`,
    SSAS_TITLE: `Scale with Azure Analysis Services`,
    TWITTER_CONNECT: 'Connect to Twitter',
    TWITTER_HANDLES_OPTIONAL: `Twitter Handles (optional):`,
    TWITTER_HANDLES_SUBTITLE: `We can enrich tweets with the tweet direction. If you would like to track whether a tweet was tweeted to or from a specific account, please explicitly list the Twitter Handles you are interested in.`,
    TWITTER_HANDLES_TITLE: `Customize your twitter handles`,
    TWITTER_SUBTITLE: `Set up a connection to your Twitter account so we can pull data. You will get to customize the search queries you want to track later on in the installation.`,
    TWITTER_TITLE: `Connect to Twitter`,
    TWITTER_VALIDATED: `Validated`,
    UNINSTALL_SUBTITLE: `The uninstaller will remove:`,
    WINDOWS_AUTH_CURRENT: `Log in as current user?`,
    WINDOWS_AUTH_PASSWORD: `Password:`,
    WINDOWS_AUTH_TITLE: `Connect to Windows`,
    WINDOWS_AUTH_USERNAME: `Windows Username:`,
    WINDOWS_AUTH_USERNAME_DESCRIPTION: `Must be in <domain>\<username> or <machinename>\<username> format`
};