SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;

CREATE TABLE dbo.optionsetmetadata
(
	entityname                 NVARCHAR(64) NOT NULL,
	optionsetname              NVARCHAR(64) NOT NULL,
	[option]                   INT NOT NULL,
	isuserlocalizedlabel       BIT NOT NULL,
	localizedlabellanguagecode INT NOT NULL,
	localizedlabel             NVARCHAR(256) NULL,
	PRIMARY KEY CLUSTERED ( entityname, optionsetname, [option], isuserlocalizedlabel, localizedlabellanguagecode )
);


CREATE TABLE dbo.statusmetadata
(
 entityname                 NVARCHAR(64) NOT NULL,
 [state]                    INT NOT NULL,
 [status]                   INT NOT NULL,
 isuserlocalizedlabel       BIT NOT NULL,
 localizedlabellanguagecode INT NOT NULL,
 localizedlabel             NVARCHAR(256) NULL,
 PRIMARY KEY CLUSTERED ( entityname, [state], [status], isuserlocalizedlabel, localizedlabellanguagecode)
);

CREATE TABLE dbo.statemetadata
(
 entityname                 NVARCHAR(64) NOT NULL,
 [state]                    INT NOT NULL,
 isuserlocalizedlabel       BIT NOT NULL,
 localizedlabellanguagecode INT NOT NULL,
 localizedlabel             NVARCHAR(256) NULL,
 PRIMARY KEY CLUSTERED ( entityname, [state], isuserlocalizedlabel, localizedlabellanguagecode)
);


CREATE TABLE dbo.globaloptionsetmetadata
(
 optionsetname              NVARCHAR(64) NOT NULL,
 [option]                   INT NOT NULL,
 isuserlocalizedlabel       BIT NOT NULL,
 localizedlabellanguagecode INT NOT NULL,
 localizedlabel             NVARCHAR(256) NULL,
 PRIMARY KEY CLUSTERED ( optionsetname, [option], isuserlocalizedlabel, localizedlabellanguagecode)
);

-- Account
CREATE TABLE dbo.account
(
  emailaddress2                            NVARCHAR(100) NULL,
  emailaddress3                            NVARCHAR(100) NULL,
  emailaddress1                            NVARCHAR(100) NULL,
  masteraccountidyominame                  NVARCHAR(4000) NULL,
  address1_city                            NVARCHAR(80) NULL,
  address1_line1                           NVARCHAR(250) NULL,
  modifiedon                               DATETIME NULL,
  aging90                                  DECIMAL(17, 2) NULL,
  overriddencreatedon                      DATETIME NULL,
  websiteurl                               NVARCHAR(200) NULL,
  address1_longitude                       FLOAT NULL,
  donotpostalmail                          TINYINT NULL,
  openrevenue                              DECIMAL(17, 2) NULL,
  address1_addresstypecode                 INT NULL,
  address1_addresstypecode_displayname     NVARCHAR(255) NULL,
  entityimage_timestamp                    BIGINT NULL,
  sharesoutstanding                        INT NULL,
  donotsendmm                              TINYINT NULL,
  primarycontactidname                     NVARCHAR(4000) NULL,
  creditonhold                             TINYINT NULL,
  transactioncurrencyidname                NVARCHAR(4000) NULL,
  aging30                                  DECIMAL(17, 2) NULL,
  donotbulkpostalmail                      TINYINT NULL,
  preferredsystemuseridyominame            NVARCHAR(4000) NULL,
  address1_shippingmethodcode              INT NULL,
  address1_shippingmethodcode_displayname  NVARCHAR(255) NULL,
  paymenttermscode                         INT NULL,
  paymenttermscode_displayname             NVARCHAR(255) NULL,
  opendeals_date                           DATETIME NULL,
  originatingleadid                        UNIQUEIDENTIFIER NULL,
  masteraccountidname                      NVARCHAR(4000) NULL,
  preferredsystemuseridname                NVARCHAR(4000) NULL,
  accountcategorycode                      INT NULL,
  accountcategorycode_displayname          NVARCHAR(255) NULL,
  address2_stateorprovince                 NVARCHAR(50) NULL,
  territoryid                              UNIQUEIDENTIFIER NULL,
  address2_country                         NVARCHAR(80) NULL,
  address2_line2                           NVARCHAR(250) NULL,
  aging60_base                             DECIMAL(19, 4) NULL,
  address1_line3                           NVARCHAR(250) NULL,
  address1_freighttermscode                INT NULL,
  address1_freighttermscode_displayname    NVARCHAR(255) NULL,
  creditlimit                              DECIMAL(17, 2) NULL,
  openrevenue_base                         DECIMAL(17, 2) NULL,
  parentaccountidname                      NVARCHAR(4000) NULL,
  originatingleadidname                    NVARCHAR(4000) NULL,
  address1_utcoffset                       INT NULL,
  preferredappointmenttimecode             INT NULL,
  preferredappointmenttimecode_displayname NVARCHAR(255) NULL,
  numberofemployees                        INT NULL,
  name                                     NVARCHAR(160) NULL,
  accountclassificationcode                INT NULL,
  accountclassificationcode_displayname    NVARCHAR(255) NULL,
  revenue                                  DECIMAL(17, 2) NULL,
  customertypecode                         INT NULL,
  customertypecode_displayname             NVARCHAR(255) NULL,
  exchangerate                             DECIMAL(22, 10) NULL,
  address2_county                          NVARCHAR(50) NULL,
  isprivate                                TINYINT NULL,
  primarycontactid                         UNIQUEIDENTIFIER NULL,
  telephone3                               NVARCHAR(50) NULL,
  parentaccountid                          UNIQUEIDENTIFIER NULL,
  address2_city                            NVARCHAR(80) NULL,
  statuscode                               INT NULL,
  statuscode_displayname                   NVARCHAR(255) NULL,
  address2_latitude                        FLOAT NULL,
  createdon                                DATETIME NULL,
  donotbulkemail                           TINYINT NULL,
  address2_line1                           NVARCHAR(250) NULL,
  donotfax                                 TINYINT NULL,
  marketcap                                DECIMAL(17, 2) NULL,
  address1_composite                       NVARCHAR(max) NULL,
  ownershipcode                            INT NULL,
  ownershipcode_displayname                NVARCHAR(255) NULL,
  opendeals_state                          INT NULL,
  owningbusinessunit                       UNIQUEIDENTIFIER NULL,
  address2_postalcode                      NVARCHAR(20) NULL,
  lastusedincampaign                       DATETIME NULL,
  utcconversiontimezonecode                INT NULL,
  owneridyominame                          NVARCHAR(4000) NULL,
  entityimage_url                          NVARCHAR(4000) NULL,
  address2_line3                           NVARCHAR(250) NULL,
  [description]                            NVARCHAR(max) NULL,
  modifiedby                               UNIQUEIDENTIFIER NULL,
  timezoneruleversionnumber                INT NULL,
  address1_county                          NVARCHAR(50) NULL,
  createdbyname                            NVARCHAR(4000) NULL,
  modifiedonbehalfby                       UNIQUEIDENTIFIER NULL,
  donotemail                               TINYINT NULL,
  territorycode                            INT NULL,
  territorycode_displayname                NVARCHAR(255) NULL,
  new_oldname                              NVARCHAR(160) NULL,
  address2_postofficebox                   NVARCHAR(20) NULL,
  address2_telephone1                      NVARCHAR(50) NULL,
  address2_telephone2                      NVARCHAR(50) NULL,
  address2_telephone3                      NVARCHAR(50) NULL,
  originatingleadidyominame                NVARCHAR(4000) NULL,
  address1_addressid                       UNIQUEIDENTIFIER NULL,
  traversedpath                            NVARCHAR(1250) NULL,
  territoryidname                          NVARCHAR(4000) NULL,
  creditlimit_base                         DECIMAL(19, 4) NULL,
  yominame                                 NVARCHAR(160) NULL,
  createdonbehalfbyname                    NVARCHAR(4000) NULL,
  owninguser                               UNIQUEIDENTIFIER NULL,
  industrycode                             INT NULL,
  industrycode_displayname                 NVARCHAR(255) NULL,
  address2_name                            NVARCHAR(200) NULL,
  openrevenue_state                        INT NULL,
  owneridtype                              NVARCHAR(255) NULL,
  entityimageid                            UNIQUEIDENTIFIER NULL,
  aging60                                  DECIMAL(17, 2) NULL,
  businesstypecode                         INT NULL,
  businesstypecode_displayname             NVARCHAR(255) NULL,
  owneridname                              NVARCHAR(4000) NULL,
  modifiedonbehalfbyname                   NVARCHAR(4000) NULL,
  createdonbehalfbyyominame                NVARCHAR(4000) NULL,
  address2_composite                       NVARCHAR(max) NULL,
  shippingmethodcode                       INT NULL,
  shippingmethodcode_displayname           NVARCHAR(255) NULL,
  address1_country                         NVARCHAR(80) NULL,
  owningteam                               UNIQUEIDENTIFIER NULL,
  address1_stateorprovince                 NVARCHAR(50) NULL,
  preferredequipmentid                     UNIQUEIDENTIFIER NULL,
  processid                                UNIQUEIDENTIFIER NULL,
  createdonbehalfby                        UNIQUEIDENTIFIER NULL,
  transactioncurrencyid                    UNIQUEIDENTIFIER NULL,
  accountratingcode                        INT NULL,
  accountratingcode_displayname            NVARCHAR(255) NULL,
  address1_telephone1                      NVARCHAR(50) NULL,
  address1_telephone2                      NVARCHAR(50) NULL,
  address1_telephone3                      NVARCHAR(50) NULL,
  address1_postofficebox                   NVARCHAR(20) NULL,
  defaultpricelevelidname                  NVARCHAR(4000) NULL,
  fax                                      NVARCHAR(50) NULL,
  masterid                                 UNIQUEIDENTIFIER NULL,
  sic                                      NVARCHAR(20) NULL,
  ownerid                                  UNIQUEIDENTIFIER NULL,
  address2_utcoffset                       INT NULL,
  stageid                                  UNIQUEIDENTIFIER NULL,
  accountnumber                            NVARCHAR(20) NULL,
  address2_fax                             NVARCHAR(50) NULL,
  revenue_base                             DECIMAL(19, 4) NULL,
  merged                                   TINYINT NULL,
  address2_longitude                       FLOAT NULL,
  defaultpricelevelid                      UNIQUEIDENTIFIER NULL,
  preferredequipmentidname                 NVARCHAR(4000) NULL,
  aging90_base                             DECIMAL(19, 4) NULL,
  donotphone                               TINYINT NULL,
  address1_primarycontactname              NVARCHAR(100) NULL,
  modifiedbyyominame                       NVARCHAR(4000) NULL,
  address1_line2                           NVARCHAR(250) NULL,
  modifiedonbehalfbyyominame               NVARCHAR(4000) NULL,
  createdby                                UNIQUEIDENTIFIER NULL,
  address2_addresstypecode                 INT NULL,
  address2_addresstypecode_displayname     NVARCHAR(255) NULL,
  openrevenue_date                         DATETIME NULL,
  address2_upszone                         NVARCHAR(4) NULL,
  marketcap_base                           DECIMAL(19, 4) NULL,
  address1_postalcode                      NVARCHAR(20) NULL,
  tickersymbol                             NVARCHAR(10) NULL,
  customersizecode                         INT NULL,
  customersizecode_displayname             NVARCHAR(255) NULL,
  preferredserviceidname                   NVARCHAR(4000) NULL,
  participatesinworkflow                   TINYINT NULL,
  stockexchange                            NVARCHAR(20) NULL,
  preferredserviceid                       UNIQUEIDENTIFIER NULL,
  preferredcontactmethodcode               INT NULL,
  preferredcontactmethodcode_displayname   NVARCHAR(255) NULL,
  importsequencenumber                     INT NULL,
  telephone2                               NVARCHAR(50) NULL,
  versionnumber                            BIGINT NULL,
  preferredsystemuserid                    UNIQUEIDENTIFIER NULL,
  accountid                                UNIQUEIDENTIFIER NULL,
  telephone1                               NVARCHAR(50) NULL,
  aging30_base                             DECIMAL(19, 4) NULL,
  address1_name                            NVARCHAR(200) NULL,
  address1_fax                             NVARCHAR(50) NULL,
  address1_latitude                        FLOAT NULL,
  address2_shippingmethodcode              INT NULL,
  address2_shippingmethodcode_displayname  NVARCHAR(255) NULL,
  primarycontactidyominame                 NVARCHAR(4000) NULL,
  preferredappointmentdaycode              INT NULL,
  preferredappointmentdaycode_displayname  NVARCHAR(255) NULL,
  modifiedbyname                           NVARCHAR(4000) NULL,
  createdbyyominame                        NVARCHAR(4000) NULL,
  address2_freighttermscode                INT NULL,
  address2_freighttermscode_displayname    NVARCHAR(255) NULL,
  address1_upszone                         NVARCHAR(4) NULL,
  address2_addressid                       UNIQUEIDENTIFIER NULL,
  ftpsiteurl                               NVARCHAR(200) NULL,
  parentaccountidyominame                  NVARCHAR(4000) NULL,
  address2_primarycontactname              NVARCHAR(100) NULL,
  opendeals                                INT NULL,
  statecode                                INT NULL,
  statecode_displayname                    NVARCHAR(255) NULL
);

-- BusinessUnit
CREATE TABLE dbo.businessunit
(
   versionnumber                           BIGINT NULL,
   address2_line2                          NVARCHAR(250) NULL,
   createdon                               DATETIME NULL,
   address1_longitude                      FLOAT NULL,
   modifiedonbehalfbyyominame              NVARCHAR(4000) NULL,
   address1_county                         NVARCHAR(50) NULL,
   address1_addressid                      UNIQUEIDENTIFIER NULL,
   address2_telephone1                     NVARCHAR(50) NULL,
   address2_telephone2                     NVARCHAR(50) NULL,
   address2_telephone3                     NVARCHAR(50) NULL,
   modifiedbyyominame                      NVARCHAR(4000) NULL,
   parentbusinessunitid                    UNIQUEIDENTIFIER NULL,
   parentbusinessunitidname                NVARCHAR(4000) NULL,
   createdonbehalfby                       UNIQUEIDENTIFIER NULL,
   address2_addressid                      UNIQUEIDENTIFIER NULL,
   inheritancemask                         INT NULL,
   ftpsiteurl                              NVARCHAR(200) NULL,
   overriddencreatedon                     DATETIME NULL,
   address2_name                           NVARCHAR(100) NULL,
   websiteurl                              NVARCHAR(200) NULL,
   address2_country                        NVARCHAR(80) NULL,
   createdonbehalfbyyominame               NVARCHAR(4000) NULL,
   address1_line1                          NVARCHAR(250) NULL,
   exchangerate                            DECIMAL(22, 10) NULL,
   address1_stateorprovince                NVARCHAR(50) NULL,
   address2_postalcode                     NVARCHAR(20) NULL,
   address2_county                         NVARCHAR(50) NULL,
   address1_country                        NVARCHAR(80) NULL,
   address1_postalcode                     NVARCHAR(20) NULL,
   address1_fax                            NVARCHAR(50) NULL,
   utcoffset                               INT NULL,
   address1_line3                          NVARCHAR(250) NULL,
   address1_utcoffset                      INT NULL,
   workflowsuspended                       TINYINT NULL,
   emailaddress                            NVARCHAR(100) NULL,
   address2_utcoffset                      INT NULL,
   address2_line1                          NVARCHAR(250) NULL,
   createdonbehalfbyname                   NVARCHAR(4000) NULL,
   address2_upszone                        NVARCHAR(4) NULL,
   address2_postofficebox                  NVARCHAR(20) NULL,
   address1_city                           NVARCHAR(80) NULL,
   tickersymbol                            NVARCHAR(10) NULL,
   picture                                 NVARCHAR(max) NULL,
   address1_telephone1                     NVARCHAR(50) NULL,
   address1_telephone2                     NVARCHAR(50) NULL,
   address1_telephone3                     NVARCHAR(50) NULL,
   modifiedon                              DATETIME NULL,
   usergroupid                             UNIQUEIDENTIFIER NULL,
   address2_stateorprovince                NVARCHAR(50) NULL,
   [description]                           NVARCHAR(max) NULL,
   address2_shippingmethodcode             INT NULL,
   address2_shippingmethodcode_displayname NVARCHAR(255) NULL,
   address1_name                           NVARCHAR(100) NULL,
   createdbyname                           NVARCHAR(4000) NULL,
   disabledreason                          NVARCHAR(500) NULL,
   isdisabled                              TINYINT NULL,
   modifiedonbehalfbyname                  NVARCHAR(4000) NULL,
   address1_shippingmethodcode             INT NULL,
   address1_shippingmethodcode_displayname NVARCHAR(255) NULL,
   address2_addresstypecode                INT NULL,
   address2_addresstypecode_displayname    NVARCHAR(255) NULL,
   address1_line2                          NVARCHAR(250) NULL,
   address2_longitude                      FLOAT NULL,
   address2_city                           NVARCHAR(80) NULL,
   calendarid                              UNIQUEIDENTIFIER NULL,
   transactioncurrencyid                   UNIQUEIDENTIFIER NULL,
   createdby                               UNIQUEIDENTIFIER NULL,
   modifiedby                              UNIQUEIDENTIFIER NULL,
   address2_fax                            NVARCHAR(50) NULL,
   stockexchange                           NVARCHAR(20) NULL,
   createdbyyominame                       NVARCHAR(4000) NULL,
   transactioncurrencyidname               NVARCHAR(4000) NULL,
   creditlimit                             FLOAT NULL,
   address1_addresstypecode                INT NULL,
   address1_addresstypecode_displayname    NVARCHAR(255) NULL,
   modifiedonbehalfby                      UNIQUEIDENTIFIER NULL,
   divisionname                            NVARCHAR(100) NULL,
   address1_latitude                       FLOAT NULL,
   name                                    NVARCHAR(160) NULL,
   address1_upszone                        NVARCHAR(4) NULL,
   modifiedbyname                          NVARCHAR(4000) NULL,
   organizationid                          UNIQUEIDENTIFIER NULL,
   address2_line3                          NVARCHAR(250) NULL,
   fileasname                              NVARCHAR(100) NULL,
   address2_latitude                       FLOAT NULL,
   organizationidname                      NVARCHAR(4000) NULL,
   costcenter                              NVARCHAR(100) NULL,
   businessunitid                          UNIQUEIDENTIFIER NULL,
   importsequencenumber                    INT NULL,
   address1_postofficebox                  NVARCHAR(20) NULL
);

-- Lead
CREATE TABLE dbo.lead
(
  contactid                               UNIQUEIDENTIFIER NULL,
  emailaddress3                           NVARCHAR(100) NULL,
  emailaddress2                           NVARCHAR(100) NULL,
  emailaddress1                           NVARCHAR(100) NULL,
  address1_city                           NVARCHAR(80) NULL,
  budgetamount_base                       DECIMAL(19, 4) NULL,
  address1_line1                          NVARCHAR(250) NULL,
  budgetstatus                            INT NULL,
  budgetstatus_displayname                NVARCHAR(255) NULL,
  modifiedon                              DATETIME NULL,
  address1_longitude                      FLOAT NULL,
  overriddencreatedon                     DATETIME NULL,
  websiteurl                              NVARCHAR(200) NULL,
  yomifirstname                           NVARCHAR(150) NULL,
  yomifullname                            NVARCHAR(450) NULL,
  accountid                               UNIQUEIDENTIFIER NULL,
  address1_addresstypecode                INT NULL,
  address1_addresstypecode_displayname    NVARCHAR(255) NULL,
  entityimage_timestamp                   BIGINT NULL,
  contactidname                           NVARCHAR(4000) NULL,
  telephone3                              NVARCHAR(50) NULL,
  confirminterest                         TINYINT NULL,
  address2_county                         NVARCHAR(50) NULL,
  transactioncurrencyidname               NVARCHAR(4000) NULL,
  address1_shippingmethodcode             INT NULL,
  address1_shippingmethodcode_displayname NVARCHAR(255) NULL,
  estimatedamount                         DECIMAL(15, 2) NULL,
  accountidname                           NVARCHAR(4000) NULL,
  relatedobjectidname                     NVARCHAR(4000) NULL,
  campaignidname                          NVARCHAR(4000) NULL,
  pager                                   NVARCHAR(20) NULL,
  masterleadidyominame                    NVARCHAR(4000) NULL,
  owningbusinessunit                      UNIQUEIDENTIFIER NULL,
  address2_stateorprovince                NVARCHAR(50) NULL,
  mobilephone                             NVARCHAR(20) NULL,
  address2_country                        NVARCHAR(80) NULL,
  address2_line2                          NVARCHAR(250) NULL,
  qualifyingopportunityid                 UNIQUEIDENTIFIER NULL,
  relatedobjectid                         UNIQUEIDENTIFIER NULL,
  owneridyominame                         NVARCHAR(4000) NULL,
  parentcontactid                         UNIQUEIDENTIFIER NULL,
  statuscode                              INT NULL,
  statuscode_displayname                  NVARCHAR(255) NULL,
  estimatedclosedate                      DATETIME NULL,
  parentaccountidname                     NVARCHAR(4000) NULL,
  address1_utcoffset                      INT NULL,
  numberofemployees                       INT NULL,
  initialcommunication                    INT NULL,
  initialcommunication_displayname        NVARCHAR(255) NULL,
  parentaccountidyominame                 NVARCHAR(4000) NULL,
  exchangerate                            DECIMAL(22, 10) NULL,
  isprivate                               TINYINT NULL,
  companyname                             NVARCHAR(100) NULL,
  parentaccountid                         UNIQUEIDENTIFIER NULL,
  address2_city                           NVARCHAR(80) NULL,
  address2_shippingmethodcode             INT NULL,
  address2_shippingmethodcode_displayname NVARCHAR(255) NULL,
  new_leadproduct                         INT NULL,
  new_leadproduct_displayname             NVARCHAR(255) NULL,
  address2_latitude                       FLOAT NULL,
  createdon                               DATETIME NULL,
  donotbulkemail                          TINYINT NULL,
  createdbyyominame                       NVARCHAR(4000) NULL,
  donotfax                                TINYINT NULL,
  address1_composite                      NVARCHAR(max) NULL,
  firstname                               NVARCHAR(50) NULL,
  createdonbehalfby                       UNIQUEIDENTIFIER NULL,
  donotpostalmail                         TINYINT NULL,
  salesstage                              INT NULL,
  salesstage_displayname                  NVARCHAR(255) NULL,
  evaluatefit                             TINYINT NULL,
  address1_country                        NVARCHAR(80) NULL,
  qualificationcomments                   NVARCHAR(max) NULL,
  address2_postalcode                     NVARCHAR(20) NULL,
  lastusedincampaign                      DATETIME NULL,
  originatingcaseid                       UNIQUEIDENTIFIER NULL,
  entityimage_url                         NVARCHAR(4000) NULL,
  address2_line3                          NVARCHAR(250) NULL,
  [description]                           NVARCHAR(max) NULL,
  modifiedby                              UNIQUEIDENTIFIER NULL,
  timezoneruleversionnumber               INT NULL,
  address1_county                         NVARCHAR(50) NULL,
  preferredcontactmethodcode              INT NULL,
  preferredcontactmethodcode_displayname  NVARCHAR(255) NULL,
  modifiedonbehalfby                      UNIQUEIDENTIFIER NULL,
  leadqualitycode                         INT NULL,
  leadqualitycode_displayname             NVARCHAR(255) NULL,
  [subject]                               NVARCHAR(300) NULL,
  address2_telephone2                     NVARCHAR(50) NULL,
  isdc_contactability                     INT NULL,
  isautocreate                            TINYINT NULL,
  address2_postofficebox                  NVARCHAR(20) NULL,
  address2_telephone1                     NVARCHAR(50) NULL,
  yomilastname                            NVARCHAR(150) NULL,
  address2_telephone3                     NVARCHAR(50) NULL,
  address1_addressid                      UNIQUEIDENTIFIER NULL,
  traversedpath                           NVARCHAR(1250) NULL,
  estimatedvalue                          FLOAT NULL,
  leadsourcecode                          INT NULL,
  leadsourcecode_displayname              NVARCHAR(255) NULL,
  owninguser                              UNIQUEIDENTIFIER NULL,
  industrycode                            INT NULL,
  industrycode_displayname                NVARCHAR(255) NULL,
  salesstagecode                          INT NULL,
  salesstagecode_displayname              NVARCHAR(255) NULL,
  address2_name                           NVARCHAR(100) NULL,
  schedulefollowup_qualify                DATETIME NULL,
  middlename                              NVARCHAR(50) NULL,
  entityimageid                           UNIQUEIDENTIFIER NULL,
  parentcontactidyominame                 NVARCHAR(4000) NULL,
  modifiedonbehalfbyname                  NVARCHAR(4000) NULL,
  createdonbehalfbyyominame               NVARCHAR(4000) NULL,
  address2_composite                      NVARCHAR(max) NULL,
  customerid                              UNIQUEIDENTIFIER NULL,
  participatesinworkflow                  TINYINT NULL,
  owningteam                              UNIQUEIDENTIFIER NULL,
  address1_stateorprovince                NVARCHAR(50) NULL,
  address1_latitude                       FLOAT NULL,
  createdonbehalfbyname                   NVARCHAR(4000) NULL,
  address1_line3                          NVARCHAR(250) NULL,
  isdc_neuralscore                        INT NULL,
  processid                               UNIQUEIDENTIFIER NULL,
  decisionmaker                           TINYINT NULL,
  revenue                                 DECIMAL(17, 2) NULL,
  jobtitle                                NVARCHAR(100) NULL,
  transactioncurrencyid                   UNIQUEIDENTIFIER NULL,
  address1_telephone1                     NVARCHAR(50) NULL,
  address1_telephone2                     NVARCHAR(50) NULL,
  address1_telephone3                     NVARCHAR(50) NULL,
  customeridyominame                      NVARCHAR(4000) NULL,
  fax                                     NVARCHAR(50) NULL,
  masterid                                UNIQUEIDENTIFIER NULL,
  yomimiddlename                          NVARCHAR(150) NULL,
  masterleadidname                        NVARCHAR(4000) NULL,
  ownerid                                 UNIQUEIDENTIFIER NULL,
  address2_utcoffset                      INT NULL,
  address2_fax                            NVARCHAR(50) NULL,
  revenue_base                            DECIMAL(19, 4) NULL,
  merged                                  TINYINT NULL,
  owneridtype                             NVARCHAR(255) NULL,
  purchasetimeframe                       INT NULL,
  purchasetimeframe_displayname           NVARCHAR(255) NULL,
  budgetamount                            DECIMAL(15, 2) NULL,
  address2_longitude                      FLOAT NULL,
  donotemail                              TINYINT NULL,
  createdbyname                           NVARCHAR(4000) NULL,
  donotphone                              TINYINT NULL,
  modifiedbyyominame                      NVARCHAR(4000) NULL,
  customeridtype                          NVARCHAR(255) NULL,
  schedulefollowup_prospect               DATETIME NULL,
  address1_line2                          NVARCHAR(250) NULL,
  donotsendmm                             TINYINT NULL,
  createdby                               UNIQUEIDENTIFIER NULL,
  address2_addresstypecode                INT NULL,
  address2_addresstypecode_displayname    NVARCHAR(255) NULL,
  address2_upszone                        NVARCHAR(4) NULL,
  salutation                              NVARCHAR(100) NULL,
  address1_postalcode                     NVARCHAR(20) NULL,
  stageid                                 UNIQUEIDENTIFIER NULL,
  utcconversiontimezonecode               INT NULL,
  leadid                                  UNIQUEIDENTIFIER NULL,
  campaignid                              UNIQUEIDENTIFIER NULL,
  qualifyingopportunityidname             NVARCHAR(4000) NULL,
  address2_addressid                      UNIQUEIDENTIFIER NULL,
  customeridname                          NVARCHAR(4000) NULL,
  importsequencenumber                    INT NULL,
  telephone2                              NVARCHAR(50) NULL,
  versionnumber                           BIGINT NULL,
  telephone1                              NVARCHAR(50) NULL,
  address1_name                           NVARCHAR(100) NULL,
  address1_fax                            NVARCHAR(50) NULL,
  contactidyominame                       NVARCHAR(4000) NULL,
  yomicompanyname                         NVARCHAR(100) NULL,
  originatingcaseidname                   NVARCHAR(4000) NULL,
  parentcontactidname                     NVARCHAR(4000) NULL,
  purchaseprocess                         INT NULL,
  purchaseprocess_displayname             NVARCHAR(255) NULL,
  modifiedbyname                          NVARCHAR(4000) NULL,
  estimatedamount_base                    DECIMAL(19, 4) NULL,
  owneridname                             NVARCHAR(4000) NULL,
  address2_line1                          NVARCHAR(250) NULL,
  address1_upszone                        NVARCHAR(4) NULL,
  lastname                                NVARCHAR(50) NULL,
  accountidyominame                       NVARCHAR(4000) NULL,
  fullname                                NVARCHAR(160) NULL,
  modifiedonbehalfbyyominame              NVARCHAR(4000) NULL,
  prioritycode                            INT NULL,
  prioritycode_displayname                NVARCHAR(255) NULL,
  need                                    INT NULL,
  need_displayname                        NVARCHAR(255) NULL,
  address1_postofficebox                  NVARCHAR(20) NULL,
  sic                                     NVARCHAR(20) NULL,
  statecode                               INT NULL,
  statecode_displayname                   NVARCHAR(255) NULL
);

-- Opportunity
CREATE TABLE dbo.opportunity
(
  contactid                         UNIQUEIDENTIFIER NULL,
  finaldecisiondate                 DATETIME NULL,
  presentfinalproposal              TINYINT NULL,
  budgetamount_base                 DECIMAL(19, 4) NULL,
  budgetstatus                      INT NULL,
  budgetstatus_displayname          NVARCHAR(255) NULL,
  modifiedon                        DATETIME NULL,
  overriddencreatedon               DATETIME NULL,
  developproposal                   TINYINT NULL,
  isrevenuesystemcalculated         TINYINT NULL,
  contactidname                     NVARCHAR(4000) NULL,
  confirminterest                   TINYINT NULL,
  proposedsolution                  NVARCHAR(max) NULL,
  freightamount                     DECIMAL(15, 2) NULL,
  transactioncurrencyidname         NVARCHAR(4000) NULL,
  new_forecast                      DECIMAL(14, 4) NULL,
  campaignidname                    NVARCHAR(4000) NULL,
  owningbusinessunit                UNIQUEIDENTIFIER NULL,
  completefinalproposal             TINYINT NULL,
  accountid                         UNIQUEIDENTIFIER NULL,
  owneridyominame                   NVARCHAR(4000) NULL,
  parentcontactid                   UNIQUEIDENTIFIER NULL,
  statuscode                        INT NULL,
  statuscode_displayname            NVARCHAR(255) NULL,
  estimatedclosedate                DATETIME NULL,
  accountidyominame                 NVARCHAR(4000) NULL,
  totallineitemamount_base          DECIMAL(19, 4) NULL,
  identifypursuitteam               TINYINT NULL,
  parentaccountidname               NVARCHAR(4000) NULL,
  originatingleadidname             NVARCHAR(4000) NULL,
  pursuitdecision                   TINYINT NULL,
  contactidyominame                 NVARCHAR(4000) NULL,
  initialcommunication              INT NULL,
  initialcommunication_displayname  NVARCHAR(255) NULL,
  parentaccountidyominame           NVARCHAR(4000) NULL,
  exchangerate                      DECIMAL(22, 10) NULL,
  parentaccountid                   UNIQUEIDENTIFIER NULL,
  filedebrief                       TINYINT NULL,
  pricelevelid                      UNIQUEIDENTIFIER NULL,
  createdon                         DATETIME NULL,
  sendthankyounote                  TINYINT NULL,
  customeridyominame                NVARCHAR(4000) NULL,
  opportunityratingcode             INT NULL,
  opportunityratingcode_displayname NVARCHAR(255) NULL,
  salesstage                        INT NULL,
  salesstage_displayname            NVARCHAR(255) NULL,
  actualclosedate                   DATETIME NULL,
  stepid                            UNIQUEIDENTIFIER NULL,
  identifycompetitors               TINYINT NULL,
  completeinternalreview            TINYINT NULL,
  evaluatefit                       TINYINT NULL,
  totallineitemdiscountamount_base  DECIMAL(19, 4) NULL,
  totaldiscountamount               DECIMAL(17, 2) NULL,
  [description]                     NVARCHAR(max) NULL,
  modifiedby                        UNIQUEIDENTIFIER NULL,
  discountamount_base               DECIMAL(19, 4) NULL,
  parentcontactidyominame           NVARCHAR(4000) NULL,
  modifiedonbehalfby                UNIQUEIDENTIFIER NULL,
  stepname                          NVARCHAR(200) NULL,
  accountidname                     NVARCHAR(4000) NULL,
  freightamount_base                DECIMAL(19, 4) NULL,
  originatingleadidyominame         NVARCHAR(4000) NULL,
  owningteam                        UNIQUEIDENTIFIER NULL,
  traversedpath                     NVARCHAR(1250) NULL,
  presentproposal                   TINYINT NULL,
  estimatedvalue                    DECIMAL(15, 2) NULL,
  createdonbehalfbyname             NVARCHAR(4000) NULL,
  owninguser                        UNIQUEIDENTIFIER NULL,
  captureproposalfeedback           TINYINT NULL,
  actualvalue_base                  DECIMAL(19, 4) NULL,
  schedulefollowup_qualify          DATETIME NULL,
  totalamountlessfreight_base       DECIMAL(19, 4) NULL,
  owneridtype                       NVARCHAR(255) NULL,
  totalamountlessfreight            DECIMAL(17, 2) NULL,
  modifiedonbehalfbyname            NVARCHAR(4000) NULL,
  createdonbehalfbyyominame         NVARCHAR(4000) NULL,
  new_forecast_base                 DECIMAL(19, 4) NULL,
  customerid                        UNIQUEIDENTIFIER NULL,
  participatesinworkflow            TINYINT NULL,
  totallineitemamount               DECIMAL(17, 2) NULL,
  qualificationcomments             NVARCHAR(max) NULL,
  opportunityid                     UNIQUEIDENTIFIER NULL,
  processid                         UNIQUEIDENTIFIER NULL,
  decisionmaker                     TINYINT NULL,
  createdonbehalfby                 UNIQUEIDENTIFIER NULL,
  transactioncurrencyid             UNIQUEIDENTIFIER NULL,
  isprivate                         TINYINT NULL,
  customerneed                      NVARCHAR(max) NULL,
  new_addtoforecast                 TINYINT NULL,
  campaignid                        UNIQUEIDENTIFIER NULL,
  resolvefeedback                   TINYINT NULL,
  actualvalue                       DECIMAL(15, 2) NULL,
  modifiedbyyominame                NVARCHAR(4000) NULL,
  ownerid                           UNIQUEIDENTIFIER NULL,
  discountpercentage                DECIMAL(5, 2) NULL,
  timeline                          INT NULL,
  timeline_displayname              NVARCHAR(255) NULL,
  originatingleadid                 UNIQUEIDENTIFIER NULL,
  scheduleproposalmeeting           DATETIME NULL,
  purchasetimeframe                 INT NULL,
  purchasetimeframe_displayname     NVARCHAR(255) NULL,
  budgetamount                      DECIMAL(15, 2) NULL,
  name                              NVARCHAR(300) NULL,
  timezoneruleversionnumber         INT NULL,
  salesstagecode                    INT NULL,
  salesstagecode_displayname        NVARCHAR(255) NULL,
  pricingerrorcode                  INT NULL,
  pricingerrorcode_displayname      NVARCHAR(255) NULL,
  createdbyname                     NVARCHAR(4000) NULL,
  statecode                         INT NULL,
  statecode_displayname             NVARCHAR(255) NULL,
  customeridtype                    NVARCHAR(255) NULL,
  schedulefollowup_prospect         DATETIME NULL,
  modifiedonbehalfbyyominame        NVARCHAR(4000) NULL,
  createdby                         UNIQUEIDENTIFIER NULL,
  estimatedvalue_base               DECIMAL(19, 4) NULL,
  totaldiscountamount_base          DECIMAL(19, 4) NULL,
  totallineitemdiscountamount       DECIMAL(17, 2) NULL,
  stageid                           UNIQUEIDENTIFIER NULL,
  utcconversiontimezonecode         INT NULL,
  customeridname                    NVARCHAR(4000) NULL,
  importsequencenumber              INT NULL,
  totalamount                       DECIMAL(17, 2) NULL,
  customerpainpoints                NVARCHAR(max) NULL,
  totalamount_base                  DECIMAL(19, 4) NULL,
  totaltax                          DECIMAL(17, 2) NULL,
  versionnumber                     BIGINT NULL,
  pricelevelidname                  NVARCHAR(4000) NULL,
  quotecomments                     NVARCHAR(max) NULL,
  discountamount                    DECIMAL(15, 2) NULL,
  totaltax_base                     DECIMAL(19, 4) NULL,
  parentcontactidname               NVARCHAR(4000) NULL,
  purchaseprocess                   INT NULL,
  purchaseprocess_displayname       NVARCHAR(255) NULL,
  modifiedbyname                    NVARCHAR(4000) NULL,
  identifycustomercontacts          TINYINT NULL,
  createdbyyominame                 NVARCHAR(4000) NULL,
  owneridname                       NVARCHAR(4000) NULL,
  prioritycode                      INT NULL,
  prioritycode_displayname          NVARCHAR(255) NULL,
  need                              INT NULL,
  need_displayname                  NVARCHAR(255) NULL,
  closeprobability                  INT NULL,
  currentsituation                  NVARCHAR(max) NULL
);
CREATE NONCLUSTERED INDEX idx_opportunity_owner_id ON dbo.opportunity(ownerid);

-- OpportunityProduct
CREATE TABLE dbo.opportunityproduct
(
  productid                               UNIQUEIDENTIFIER NULL,
  entityimage_timestamp                   BIGINT NULL,
  createdon                               DATETIME NULL,
  modifiedonbehalfbyyominame              NVARCHAR(4000) NULL,
  manualdiscountamount                    DECIMAL(17, 2) NULL,
  modifiedbyyominame                      NVARCHAR(4000) NULL,
  opportunityidname                       NVARCHAR(4000) NULL,
  owneridtype                             NVARCHAR(255) NULL,
  productdescription                      NVARCHAR(500) NULL,
  overriddencreatedon                     DATETIME NULL,
  parentbundleid                          UNIQUEIDENTIFIER NULL,
  baseamount                              DECIMAL(17, 2) NULL,
  modifiedonbehalfby                      UNIQUEIDENTIFIER NULL,
  exchangerate                            DECIMAL(22, 10) NULL,
  baseamount_base                         DECIMAL(19, 4) NULL,
  priceperunit                            DECIMAL(17, 2) NULL,
  timezoneruleversionnumber               INT NULL,
  opportunityid                           UNIQUEIDENTIFIER NULL,
  owninguser                              UNIQUEIDENTIFIER NULL,
  versionnumber                           BIGINT NULL,
  sequencenumber                          INT NULL,
  priceperunit_base                       DECIMAL(19, 4) NULL,
  uomidname                               NVARCHAR(4000) NULL,
  tax_base                                DECIMAL(19, 4) NULL,
  createdby                               UNIQUEIDENTIFIER NULL,
  utcconversiontimezonecode               INT NULL,
  uomid                                   UNIQUEIDENTIFIER NULL,
  producttypecode                         INT NULL,
  producttypecode_displayname             NVARCHAR(255) NULL,
  ownerid                                 UNIQUEIDENTIFIER NULL,
  modifiedon                              DATETIME NULL,
  importsequencenumber                    INT NULL,
  isproductoverridden                     TINYINT NULL,
  modifiedby                              UNIQUEIDENTIFIER NULL,
  manualdiscountamount_base               DECIMAL(19, 4) NULL,
  [description]                           NVARCHAR(max) NULL,
  entityimageid                           UNIQUEIDENTIFIER NULL,
  createdbyname                           NVARCHAR(4000) NULL,
  ispriceoverridden                       TINYINT NULL,
  modifiedonbehalfbyname                  NVARCHAR(4000) NULL,
  opportunityproductid                    UNIQUEIDENTIFIER NULL,
  transactioncurrencyid                   UNIQUEIDENTIFIER NULL,
  createdonbehalfby                       UNIQUEIDENTIFIER NULL,
  pricingerrorcode                        INT NULL,
  pricingerrorcode_displayname            NVARCHAR(255) NULL,
  createdbyyominame                       NVARCHAR(4000) NULL,
  volumediscountamount_base               DECIMAL(19, 4) NULL,
  transactioncurrencyidname               NVARCHAR(4000) NULL,
  createdonbehalfbyyominame               NVARCHAR(4000) NULL,
  owningbusinessunit                      UNIQUEIDENTIFIER NULL,
  createdonbehalfbyname                   NVARCHAR(4000) NULL,
  quantity                                DECIMAL(17, 5) NULL,
  extendedamount_base                     DECIMAL(19, 4) NULL,
  opportunitystatecode                    INT NULL,
  opportunitystatecode_displayname        NVARCHAR(255) NULL,
  propertyconfigurationstatus             INT NULL,
  propertyconfigurationstatus_displayname NVARCHAR(255) NULL,
  productidname                           NVARCHAR(4000) NULL,
  extendedamount                          DECIMAL(17, 2) NULL,
  modifiedbyname                          NVARCHAR(4000) NULL,
  lineitemnumber                          INT NULL,
  volumediscountamount                    DECIMAL(17, 2) NULL,
  tax                                     DECIMAL(17, 2) NULL,
  entityimage_url                         NVARCHAR(4000) NULL,
  productassociationid                    UNIQUEIDENTIFIER NULL
);


-- Product
CREATE TABLE dbo.product
(
    iskit                        TINYINT          NULL,
    productid                    UNIQUEIDENTIFIER NULL,
    entityimage_timestamp        BIGINT           NULL,
    createdon                    DATETIME         NULL,
    standardcost_base            DECIMAL(19, 4)  NULL,
    createdbyname                NVARCHAR(4000)  NULL,
    parentproductidname          NVARCHAR(4000)  NULL,
    modifiedbyyominame           NVARCHAR(4000)  NULL,
    productstructure             INT              NULL,
    productstructure_displayname NVARCHAR(255)   NULL,
    modifiedbyname               NVARCHAR(4000)  NULL,
    defaultuomidname             NVARCHAR(4000)  NULL,
    validfromdate                DATETIME         NULL,
    price_base                   DECIMAL(19, 4)  NULL,
    currentcost                  DECIMAL(15, 2)  NULL,
    defaultuomscheduleidname     NVARCHAR(4000)  NULL,
    createdonbehalfbyyominame    NVARCHAR(4000)  NULL,
    modifiedonbehalfby           UNIQUEIDENTIFIER NULL,
    exchangerate                 DECIMAL(22, 10) NULL,
    overriddencreatedon          DATETIME         NULL,
    producturl                   NVARCHAR(255)   NULL,
    statecode                    INT              NULL,
    statecode_displayname        NVARCHAR(255)   NULL,
    price                        DECIMAL(15, 2)  NULL,
    defaultuomscheduleid         UNIQUEIDENTIFIER NULL,
    timezoneruleversionnumber    INT              NULL,
    size                         NVARCHAR(200)   NULL,
    pricelevelid                 UNIQUEIDENTIFIER NULL,
    versionnumber                BIGINT           NULL,
    traversedpath                NVARCHAR(1250)  NULL,
    createdonbehalfbyname        NVARCHAR(4000)  NULL,
    createdbyyominame            NVARCHAR(4000)  NULL,
    createdonbehalfby            UNIQUEIDENTIFIER NULL,
    utcconversiontimezonecode    INT              NULL,
    vendorname                   NVARCHAR(100)   NULL,
    producttypecode              INT              NULL,
    producttypecode_displayname  NVARCHAR(255)   NULL,
    vendorpartnumber             NVARCHAR(100)   NULL,
    modifiedon                   DATETIME         NULL,
    importsequencenumber         INT              NULL,
    processid                    UNIQUEIDENTIFIER NULL,
    [description]                NVARCHAR(MAX)   NULL,
    parentproductid              UNIQUEIDENTIFIER NULL,
    modifiedonbehalfbyname       NVARCHAR(4000)  NULL,
    subjectid                    UNIQUEIDENTIFIER NULL,
    subjectidname                NVARCHAR(4000)  NULL,
    stageid                      UNIQUEIDENTIFIER NULL,
    defaultuomid                 UNIQUEIDENTIFIER NULL,
    stockvolume                  DECIMAL(12, 2)  NULL,
    quantitydecimal              INT              NULL,
    transactioncurrencyid        UNIQUEIDENTIFIER NULL,
    isstockitem                  TINYINT          NULL,
    quantityonhand               DECIMAL(12, 2)  NULL,
    createdby                    UNIQUEIDENTIFIER NULL,
    pricelevelidname             NVARCHAR(4000)  NULL,
    modifiedby                   UNIQUEIDENTIFIER NULL,
    transactioncurrencyidname    NVARCHAR(4000)  NULL,
    vendorid                     NVARCHAR(100)   NULL,
    currentcost_base             DECIMAL(19, 4)  NULL,
    hierarchypath                NVARCHAR(450)   NULL,
    suppliername                 NVARCHAR(100)   NULL,
    validtodate                  DATETIME         NULL,
    name                         NVARCHAR(100)   NULL,
    entityimage_url              NVARCHAR(4000)  NULL,
    stockweight                  DECIMAL(12, 2)  NULL,
    statuscode                   INT              NULL,
    statuscode_displayname       NVARCHAR(255)   NULL,
    modifiedonbehalfbyyominame   NVARCHAR(4000)  NULL,
    dmtimportstate               INT              NULL,
    organizationid               UNIQUEIDENTIFIER NULL,
    productnumber                NVARCHAR(100)   NULL,
    entityimageid                UNIQUEIDENTIFIER NULL,
    organizationidname           NVARCHAR(4000)  NULL,
    standardcost                 DECIMAL(15, 2)  NULL
);


-- SystemUser
CREATE TABLE dbo.systemuser
(
  traversedpath                           NVARCHAR(1250) NULL,
  address1_city                           NVARCHAR(128) NULL,
  address1_line1                          NVARCHAR(1024) NULL,
  internalemailaddress                    NVARCHAR(100) NULL,
  siteidname                              NVARCHAR(4000) NULL,
  modifiedon                              DATETIME NULL,
  skills                                  NVARCHAR(100) NULL,
  yomifirstname                           NVARCHAR(64) NULL,
  address1_longitude                      FLOAT NULL,
  yomifullname                            NVARCHAR(200) NULL,
  address1_addresstypecode                INT NULL,
  address1_addresstypecode_displayname    NVARCHAR(255) NULL,
  entityimage_timestamp                   BIGINT NULL,
  parentsystemuseridname                  NVARCHAR(4000) NULL,
  address2_county                         NVARCHAR(128) NULL,
  transactioncurrencyidname               NVARCHAR(4000) NULL,
  activedirectoryguid                     UNIQUEIDENTIFIER NULL,
  title                                   NVARCHAR(128) NULL,
  address1_shippingmethodcode             INT NULL,
  address1_shippingmethodcode_displayname NVARCHAR(255) NULL,
  utcconversiontimezonecode               INT NULL,
  passporthi                              INT NULL,
  homephone                               NVARCHAR(50) NULL,
  parentsystemuseridyominame              NVARCHAR(4000) NULL,
  address2_stateorprovince                NVARCHAR(128) NULL,
  territoryid                             UNIQUEIDENTIFIER NULL,
  address2_country                        NVARCHAR(128) NULL,
  address2_name                           NVARCHAR(100) NULL,
  disabledreason                          NVARCHAR(500) NULL,
  address1_line3                          NVARCHAR(1024) NULL,
  caltype                                 INT NULL,
  caltype_displayname                     NVARCHAR(255) NULL,
  calendarid                              UNIQUEIDENTIFIER NULL,
  setupuser                               TINYINT NULL,
  address1_utcoffset                      INT NULL,
  msdyusd_usdconfigurationidname          NVARCHAR(4000) NULL,
  islicensed                              TINYINT NULL,
  isactivedirectoryuser                   TINYINT NULL,
  userlicensetype                         INT NULL,
  exchangerate                            DECIMAL(22, 10) NULL,
  preferredemailcode                      INT NULL,
  preferredemailcode_displayname          NVARCHAR(255) NULL,
  address2_city                           NVARCHAR(128) NULL,
  passportlo                              INT NULL,
  address2_latitude                       FLOAT NULL,
  createdon                               DATETIME NULL,
  queueid                                 UNIQUEIDENTIFIER NULL,
  yomimiddlename                          NVARCHAR(50) NULL,
  firstname                               NVARCHAR(64) NULL,
  address2_postalcode                     NVARCHAR(40) NULL,
  displayinserviceviews                   TINYINT NULL,
  employeeid                              NVARCHAR(100) NULL,
  processid                               UNIQUEIDENTIFIER NULL,
  parentsystemuserid                      UNIQUEIDENTIFIER NULL,
  governmentid                            NVARCHAR(100) NULL,
  entityimage_url                         NVARCHAR(4000) NULL,
  address2_line3                          NVARCHAR(1024) NULL,
  modifiedby                              UNIQUEIDENTIFIER NULL,
  outgoingemaildeliverymethod             INT NULL,
  outgoingemaildeliverymethod_displayname NVARCHAR(255) NULL,
  timezoneruleversionnumber               INT NULL,
  address1_county                         NVARCHAR(128) NULL,
  createdbyname                           NVARCHAR(4000) NULL,
  modifiedonbehalfby                      UNIQUEIDENTIFIER NULL,
  address2_telephone2                     NVARCHAR(50) NULL,
  preferredphonecode                      INT NULL,
  preferredphonecode_displayname          NVARCHAR(255) NULL,
  address2_postofficebox                  NVARCHAR(40) NULL,
  address2_telephone1                     NVARCHAR(50) NULL,
  yomilastname                            NVARCHAR(64) NULL,
  address2_telephone3                     NVARCHAR(50) NULL,
  address1_addressid                      UNIQUEIDENTIFIER NULL,
  emailrouteraccessapproval               INT NULL,
  emailrouteraccessapproval_displayname   NVARCHAR(255) NULL,
  territoryidname                         NVARCHAR(4000) NULL,
  createdonbehalfbyname                   NVARCHAR(4000) NULL,
  systemuserid                            UNIQUEIDENTIFIER NULL,
  defaultmailbox                          UNIQUEIDENTIFIER NULL,
  middlename                              NVARCHAR(50) NULL,
  msdyusd_usdconfigurationid              UNIQUEIDENTIFIER NULL,
  entityimageid                           UNIQUEIDENTIFIER NULL,
  address2_line2                          NVARCHAR(1024) NULL,
  modifiedonbehalfbyname                  NVARCHAR(4000) NULL,
  overriddencreatedon                     DATETIME NULL,
  mobilephone                             NVARCHAR(64) NULL,
  address2_composite                      NVARCHAR(max) NULL,
  address1_country                        NVARCHAR(128) NULL,
  mobilealertemail                        NVARCHAR(100) NULL,
  sharepointemailaddress                  NVARCHAR(1024) NULL,
  businessunitidname                      NVARCHAR(4000) NULL,
  address1_stateorprovince                NVARCHAR(128) NULL,
  positionid                              UNIQUEIDENTIFIER NULL,
  address2_utcoffset                      INT NULL,
  preferredaddresscode                    INT NULL,
  preferredaddresscode_displayname        NVARCHAR(255) NULL,
  incomingemaildeliverymethod             INT NULL,
  incomingemaildeliverymethod_displayname NVARCHAR(255) NULL,
  createdonbehalfby                       UNIQUEIDENTIFIER NULL,
  jobtitle                                NVARCHAR(100) NULL,
  nickname                                NVARCHAR(50) NULL,
  transactioncurrencyid                   UNIQUEIDENTIFIER NULL,
  address1_telephone1                     NVARCHAR(64) NULL,
  address1_telephone2                     NVARCHAR(50) NULL,
  address1_telephone3                     NVARCHAR(50) NULL,
  address1_postofficebox                  NVARCHAR(40) NULL,
  organizationid                          UNIQUEIDENTIFIER NULL,
  yammeremailaddress                      NVARCHAR(200) NULL,
  defaultmailboxname                      NVARCHAR(4000) NULL,
  defaultfilterspopulated                 TINYINT NULL,
  siteid                                  UNIQUEIDENTIFIER NULL,
  photourl                                NVARCHAR(200) NULL,
  accessmode                              INT NULL,
  accessmode_displayname                  NVARCHAR(255) NULL,
  personalemailaddress                    NVARCHAR(100) NULL,
  isintegrationuser                       TINYINT NULL,
  address2_longitude                      FLOAT NULL,
  domainname                              NVARCHAR(1024) NULL,
  modifiedbyyominame                      NVARCHAR(4000) NULL,
  address2_fax                            NVARCHAR(50) NULL,
  createdonbehalfbyyominame               NVARCHAR(4000) NULL,
  address1_line2                          NVARCHAR(1024) NULL,
  modifiedonbehalfbyyominame              NVARCHAR(4000) NULL,
  createdby                               UNIQUEIDENTIFIER NULL,
  address2_addresstypecode                INT NULL,
  address2_addresstypecode_displayname    NVARCHAR(255) NULL,
  windowsliveid                           NVARCHAR(1024) NULL,
  salutation                              NVARCHAR(20) NULL,
  address1_postalcode                     NVARCHAR(40) NULL,
  stageid                                 UNIQUEIDENTIFIER NULL,
  address2_upszone                        NVARCHAR(4) NULL,
  address1_composite                      NVARCHAR(max) NULL,
  positionidname                          NVARCHAR(4000) NULL,
  address2_addressid                      UNIQUEIDENTIFIER NULL,
  yammeruserid                            NVARCHAR(128) NULL,
  importsequencenumber                    INT NULL,
  isemailaddressapprovedbyo365admin       TINYINT NULL,
  invitestatuscode                        INT NULL,
  invitestatuscode_displayname            NVARCHAR(255) NULL,
  organizationidname                      NVARCHAR(4000) NULL,
  versionnumber                           BIGINT NULL,
  queueidname                             NVARCHAR(4000) NULL,
  issyncwithdirectory                     TINYINT NULL,
  address1_name                           NVARCHAR(100) NULL,
  address1_fax                            NVARCHAR(64) NULL,
  address1_latitude                       FLOAT NULL,
  businessunitid                          UNIQUEIDENTIFIER NULL,
  address2_shippingmethodcode             INT NULL,
  address2_shippingmethodcode_displayname NVARCHAR(255) NULL,
  modifiedbyname                          NVARCHAR(4000) NULL,
  createdbyyominame                       NVARCHAR(4000) NULL,
  address2_line1                          NVARCHAR(1024) NULL,
  address1_upszone                        NVARCHAR(4) NULL,
  lastname                                NVARCHAR(64) NULL,
  fullname                                NVARCHAR(200) NULL,
  isdisabled                              TINYINT NULL,
  reassignprincipalid                     UNIQUEIDENTIFIER NULL,
  reassignprincipalidtype                 NVARCHAR(255) NULL
);


-- SystemUserManagerMap
-- CRM internal table
CREATE TABLE dbo.systemusermanagermap
(
  hierarchylevel         INT NULL,
  versionnumber          BIGINT NULL,
  parentsystemuserid     UNIQUEIDENTIFIER NULL,
  systemusermanagermapid UNIQUEIDENTIFIER NULL,
  systemuserid           UNIQUEIDENTIFIER NULL
);
CREATE INDEX idx_systemusermanagermap_systemuser_id ON dbo.systemusermanagermap(systemuserid) INCLUDE (parentsystemuserid);


-- Territory
-- CRM internal table
CREATE TABLE dbo.territory
(
  createdonbehalfbyyominame  NVARCHAR(4000) NULL,
  modifiedonbehalfby         UNIQUEIDENTIFIER NULL,
  transactioncurrencyidname  NVARCHAR(4000) NULL,
  manageridname              NVARCHAR(4000) NULL,
  entityimage_timestamp      BIGINT NULL,
  managerid                  UNIQUEIDENTIFIER NULL,
  createdonbehalfby          UNIQUEIDENTIFIER NULL,
  transactioncurrencyid      UNIQUEIDENTIFIER NULL,
  name                       NVARCHAR(200) NULL,
  entityimageid              UNIQUEIDENTIFIER NULL,
  importsequencenumber       INT NULL,
  organizationid             UNIQUEIDENTIFIER NULL,
  createdbyyominame          NVARCHAR(4000) NULL,
  territoryid                UNIQUEIDENTIFIER NULL,
  modifiedbyname             NVARCHAR(4000) NULL,
  versionnumber              BIGINT NULL,
  modifiedby                 UNIQUEIDENTIFIER NULL,
  modifiedbyyominame         NVARCHAR(4000) NULL,
  createdby                  UNIQUEIDENTIFIER NULL,
  organizationidname         NVARCHAR(4000) NULL,
  modifiedon                 DATETIME NULL,
  exchangerate               DECIMAL(22, 10) NULL,
  manageridyominame          NVARCHAR(4000) NULL,
  modifiedonbehalfbyyominame NVARCHAR(4000) NULL,
  createdbyname              NVARCHAR(4000) NULL,
  createdon                  DATETIME NULL,
  createdonbehalfbyname      NVARCHAR(4000) NULL,
  [description]              NVARCHAR(max) NULL,
  modifiedonbehalfbyname     NVARCHAR(4000) NULL,
  overriddencreatedon        DATETIME NULL,
  entityimage_url            NVARCHAR(4000) NULL
);



/* SMGT specific schemas */
CREATE TABLE smgt.actualsales
(
  invoiceid   VARCHAR(50) NULL,
  actualsales DECIMAL NULL,
  invoicedate DATE NULL,
  accountid   VARCHAR(50) NULL,
  productid   VARCHAR(50) NULL
);


CREATE TABLE smgt.configuration
(
  id                     INT IDENTITY(1, 1) NOT NULL,
  configuration_group    VARCHAR(150) NOT NULL,
  configuration_subgroup VARCHAR(150) NOT NULL,
  name                   VARCHAR(150) NOT NULL,
  value                  VARCHAR(max) NULL,
  visible                BIT NOT NULL DEFAULT 0
);


CREATE TABLE smgt.[date]
(
   date_key               INT NOT NULL,
   full_date              DATE NOT NULL,
   day_of_week            TINYINT NOT NULL,
   day_num_in_month       TINYINT NOT NULL,
   day_name               CHAR(9) NOT NULL,
   day_abbrev             CHAR(3) NOT NULL,
   weekday_flag           CHAR(1) NOT NULL,
   week_num_in_year       TINYINT NOT NULL,
   week_begin_date        DATE NOT NULL,
   week_begin_date_key    INT NOT NULL,
   [month]                TINYINT NOT NULL,
   month_name             CHAR(9) NOT NULL,
   month_abbrev           CHAR(3) NOT NULL,
   [quarter]              TINYINT NOT NULL,
   [year]                 SMALLINT NOT NULL,
   yearmo                 INT NOT NULL,
   fiscal_month           TINYINT NOT NULL,
   fiscal_quarter         TINYINT NOT NULL,
   fiscal_year            SMALLINT NOT NULL,
   last_day_in_month_flag CHAR(1) NOT NULL,
   same_day_year_ago_date DATE NOT NULL,
   same_day_year_ago_key  INT NOT NULL,
   day_num_in_year           AS Datepart(dayofyear, full_date),
   quarter_name              AS Concat('Q', [quarter]),
   fiscal_quarter_name       AS Concat('Q', fiscal_quarter),
   fiscalquartercompletename AS Concat('FY', Substring(CONVERT(VARCHAR, fiscal_year), 3, 2), ' Q', fiscal_quarter),
   fiscalyearcompletename    AS Concat('FY', Substring(CONVERT(VARCHAR, fiscal_year), 3, 2)),
   fiscalmonthcompletename   AS Concat(month_abbrev, ' ', Substring(CONVERT(VARCHAR, fiscal_year), 3, 2)),
   CONSTRAINT pk_dim_date PRIMARY KEY CLUSTERED (date_key)
);


CREATE TABLE smgt.quotas
(
  [amount]    DECIMAL(18, 0) NULL,
  [date]      DATE NULL,
  ownerid     VARCHAR(50) NULL,
  productid   VARCHAR(50) NULL
);


CREATE TABLE smgt.targets
(
  productid      VARCHAR(50) NULL,
  businessunitid VARCHAR(50) NULL,
  territoryid    VARCHAR(50) NULL,
  [target]       DECIMAL NULL,
  [date]         DATE NULL
);


CREATE TABLE smgt.usermapping
(
    userid     VARCHAR(50) NULL,
    domainuser VARCHAR(50) NULL
);