SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

-- Must be executed inside the target database
-- Views

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_FullDocument' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_FullDocument;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documentsentimentscores' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documentsentimentscores;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documentkeyphrases' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documentkeyphrases;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_fulldocumenttopics' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_fulldocumenttopics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documenttopicimages' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documenttopicimages;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documentcompressedentities' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documentcompressedentities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_fullentities' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_fullentities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_entityrankings' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_entityrankings;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_documents' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_documents;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_date' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_date;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='vw_configuration' AND TABLE_TYPE='VIEW')
    DROP VIEW bpst_news.vw_configuration;

-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentingestedtimes' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documentingestedtimes;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentsentimentscores' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documentsentimentscores;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentkeyphrases' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documentkeyphrases;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documenttopics' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documenttopics;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documenttopicimages' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documenttopicimages;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentcompressedentities' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.documentcompressedentities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='entities' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.entities;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documents' AND TABLE_TYPE='BASE TABLE')
	DROP TABLE bpst_news.documents;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='documentpublishedtimes' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.documentpublishedtimes;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='date' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.[date];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='bpst_news' AND TABLE_NAME='configuration' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE bpst_news.[configuration];



-- Stored procedures
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_get_replication_counts' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_get_replication_counts;
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='bpst_news' AND ROUTINE_NAME='sp_get_prior_content' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE bpst_news.sp_get_prior_content;


IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='bpst_news')
BEGIN
    EXEC ('CREATE SCHEMA bpst_news AUTHORIZATION dbo'); -- Avoid batch error
END;
