SET ANSI_NULLS              ON;
SET ANSI_PADDING            ON;
SET ANSI_WARNINGS           ON;
SET ANSI_NULL_DFLT_ON       ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET QUOTED_IDENTIFIER       ON;
go

-- Must be executed inside the target database
-- Views
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sap' AND TABLE_NAME='vw_configuration' AND TABLE_TYPE='VIEW')
    DROP VIEW sap.vw_configuration;


-- Tables
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='ActivityLog' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE dbo.[ActivityLog];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sap' AND TABLE_NAME='configuration' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE sap.[configuration];
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='sap' AND TABLE_NAME='sap_replicationstatus' AND TABLE_TYPE='BASE TABLE')
    DROP TABLE sap.sap_replicationstatus;


-- Stored procedures
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA='sap' AND ROUTINE_NAME='sp_get_replication_counts' AND ROUTINE_TYPE='PROCEDURE')
    DROP PROCEDURE sap.sp_get_replication_counts;


IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name='sap')
BEGIN
    EXEC ('CREATE SCHEMA sap AUTHORIZATION dbo'); -- Avoid batch error
END;
